library flutter_feather_icons;

import "package:flutter/widgets.dart";
import "package:flutter_feather_icons/src/icon_data.dart";

// THIS FILE IS AUTOMATICALLY GENERATED!

@staticIconProvider
abstract final class FeatherIcons {
  static const IconData activity = IconData(0xe900,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData airplay = IconData(0xe901,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData alertCircle = IconData(0xe902,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData alertOctagon = IconData(0xe903,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData alertTriangle = IconData(0xe904,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData alignCenter = IconData(0xe905,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData alignJustify = IconData(0xe906,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData alignLeft = IconData(0xe907,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData alignRight = IconData(0xe908,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData anchor = IconData(0xe909,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData aperture = IconData(0xe90a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData archive = IconData(0xe90b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowDownCircle = IconData(0xe90c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowDownLeft = IconData(0xe90d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowDownRight = IconData(0xe90e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowDown = IconData(0xe90f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowLeftCircle = IconData(0xe910,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowLeft = IconData(0xe911,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowRightCircle = IconData(0xe912,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowRight = IconData(0xe913,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowUpCircle = IconData(0xe914,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowUpLeft = IconData(0xe915,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowUpRight = IconData(0xe916,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData arrowUp = IconData(0xe917,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData atSign = IconData(0xe918,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData award = IconData(0xe919,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData barChart2 = IconData(0xe91a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData barChart = IconData(0xe91b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData batteryCharging = IconData(0xe91c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData battery = IconData(0xe91d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData bellOff = IconData(0xe91e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData bell = IconData(0xe91f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData bluetooth = IconData(0xe920,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData bold = IconData(0xe921,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData bookOpen = IconData(0xe922,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData book = IconData(0xe923,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData bookmark = IconData(0xe924,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData box = IconData(0xe925,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData briefcase = IconData(0xe926,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData calendar = IconData(0xe927,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cameraOff = IconData(0xe928,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData camera = IconData(0xe929,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cast = IconData(0xe92a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData checkCircle = IconData(0xe92b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData checkSquare = IconData(0xe92c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData check = IconData(0xe92d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronDown = IconData(0xe92e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronLeft = IconData(0xe92f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronRight = IconData(0xe930,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronUp = IconData(0xe931,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronsDown = IconData(0xe932,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronsLeft = IconData(0xe933,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronsRight = IconData(0xe934,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chevronsUp = IconData(0xe935,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData chrome = IconData(0xe936,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData circle = IconData(0xe937,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData clipboard = IconData(0xe938,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData clock = IconData(0xe939,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cloudDrizzle = IconData(0xe93a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cloudLightning = IconData(0xe93b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cloudOff = IconData(0xe93c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cloudRain = IconData(0xe93d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cloudSnow = IconData(0xe93e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cloud = IconData(0xe93f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData code = IconData(0xe940,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData codepen = IconData(0xe941,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData codesandbox = IconData(0xe942,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData coffee = IconData(0xe943,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData columns = IconData(0xe944,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData command = IconData(0xe945,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData compass = IconData(0xe946,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData copy = IconData(0xe947,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerDownLeft = IconData(0xe948,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerDownRight = IconData(0xe949,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerLeftDown = IconData(0xe94a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerLeftUp = IconData(0xe94b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerRightDown = IconData(0xe94c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerRightUp = IconData(0xe94d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerUpLeft = IconData(0xe94e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cornerUpRight = IconData(0xe94f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData cpu = IconData(0xe950,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData creditCard = IconData(0xe951,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData crop = IconData(0xe952,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData crosshair = IconData(0xe953,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData database = IconData(0xe954,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData delete = IconData(0xe955,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData disc = IconData(0xe956,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData dollarSign = IconData(0xe957,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData downloadCloud = IconData(0xe958,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData download = IconData(0xe959,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData droplet = IconData(0xe95a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData edit2 = IconData(0xe95b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData edit3 = IconData(0xe95c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData edit = IconData(0xe95d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData externalLink = IconData(0xe95e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData eyeOff = IconData(0xe95f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData eye = IconData(0xe960,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData facebook = IconData(0xe961,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData fastForward = IconData(0xe962,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData feather = IconData(0xe963,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData figma = IconData(0xe964,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData fileMinus = IconData(0xe965,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData filePlus = IconData(0xe966,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData fileText = IconData(0xe967,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData file = IconData(0xe968,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData film = IconData(0xe969,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData filter = IconData(0xe96a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData flag = IconData(0xe96b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData folderMinus = IconData(0xe96c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData folderPlus = IconData(0xe96d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData folder = IconData(0xe96e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData framer = IconData(0xe96f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData frown = IconData(0xe970,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData gift = IconData(0xe971,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData gitBranch = IconData(0xe972,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData gitCommit = IconData(0xe973,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData gitMerge = IconData(0xe974,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData gitPullRequest = IconData(0xe975,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData github = IconData(0xe976,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData gitlab = IconData(0xe977,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData globe = IconData(0xe978,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData grid = IconData(0xe979,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData hardDrive = IconData(0xe97a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData hash = IconData(0xe97b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData headphones = IconData(0xe97c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData heart = IconData(0xe97d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData helpCircle = IconData(0xe97e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData hexagon = IconData(0xe97f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData home = IconData(0xe980,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData image = IconData(0xe981,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData inbox = IconData(0xe982,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData info = IconData(0xe983,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData instagram = IconData(0xe984,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData italic = IconData(0xe985,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData key = IconData(0xe986,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData layers = IconData(0xe987,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData layout = IconData(0xe988,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData lifeBuoy = IconData(0xe989,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData link2 = IconData(0xe98a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData link = IconData(0xe98b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData linkedin = IconData(0xe98c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData list = IconData(0xe98d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData loader = IconData(0xe98e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData lock = IconData(0xe98f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData logIn = IconData(0xe990,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData logOut = IconData(0xe991,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData mail = IconData(0xe992,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData mapPin = IconData(0xe993,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData map = IconData(0xe994,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData maximize2 = IconData(0xe995,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData maximize = IconData(0xe996,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData meh = IconData(0xe997,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData menu = IconData(0xe998,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData messageCircle = IconData(0xe999,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData messageSquare = IconData(0xe99a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData micOff = IconData(0xe99b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData mic = IconData(0xe99c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData minimize2 = IconData(0xe99d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData minimize = IconData(0xe99e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData minusCircle = IconData(0xe99f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData minusSquare = IconData(0xe9a0,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData minus = IconData(0xe9a1,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData monitor = IconData(0xe9a2,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData moon = IconData(0xe9a3,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData moreHorizontal = IconData(0xe9a4,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData moreVertical = IconData(0xe9a5,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData mousePointer = IconData(0xe9a6,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData move = IconData(0xe9a7,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData music = IconData(0xe9a8,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData navigation2 = IconData(0xe9a9,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData navigation = IconData(0xe9aa,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData octagon = IconData(0xe9ab,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData package = IconData(0xe9ac,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData paperclip = IconData(0xe9ad,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData pauseCircle = IconData(0xe9ae,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData pause = IconData(0xe9af,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData penTool = IconData(0xe9b0,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData percent = IconData(0xe9b1,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData phoneCall = IconData(0xe9b2,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData phoneForwarded = IconData(0xe9b3,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData phoneIncoming = IconData(0xe9b4,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData phoneMissed = IconData(0xe9b5,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData phoneOff = IconData(0xe9b6,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData phoneOutgoing = IconData(0xe9b7,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData phone = IconData(0xe9b8,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData pieChart = IconData(0xe9b9,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData playCircle = IconData(0xe9ba,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData play = IconData(0xe9bb,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData plusCircle = IconData(0xe9bc,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData plusSquare = IconData(0xe9bd,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData plus = IconData(0xe9be,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData pocket = IconData(0xe9bf,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData power = IconData(0xe9c0,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData printer = IconData(0xe9c1,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData radio = IconData(0xe9c2,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData refreshCcw = IconData(0xe9c3,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData refreshCw = IconData(0xe9c4,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData repeat = IconData(0xe9c5,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData rewind = IconData(0xe9c6,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData rotateCcw = IconData(0xe9c7,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData rotateCw = IconData(0xe9c8,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData rss = IconData(0xe9c9,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData save = IconData(0xe9ca,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData scissors = IconData(0xe9cb,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData search = IconData(0xe9cc,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData send = IconData(0xe9cd,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData server = IconData(0xe9ce,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData settings = IconData(0xe9cf,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData share2 = IconData(0xe9d0,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData share = IconData(0xe9d1,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData shieldOff = IconData(0xe9d2,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData shield = IconData(0xe9d3,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData shoppingBag = IconData(0xe9d4,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData shoppingCart = IconData(0xe9d5,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData shuffle = IconData(0xe9d6,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData sidebar = IconData(0xe9d7,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData skipBack = IconData(0xe9d8,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData skipForward = IconData(0xe9d9,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData slack = IconData(0xe9da,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData slash = IconData(0xe9db,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData sliders = IconData(0xe9dc,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData smartphone = IconData(0xe9dd,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData smile = IconData(0xe9de,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData speaker = IconData(0xe9df,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData square = IconData(0xe9e0,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData star = IconData(0xe9e1,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData stopCircle = IconData(0xe9e2,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData sun = IconData(0xe9e3,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData sunrise = IconData(0xe9e4,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData sunset = IconData(0xe9e5,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData tablet = IconData(0xe9e6,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData tag = IconData(0xe9e7,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData target = IconData(0xe9e8,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData terminal = IconData(0xe9e9,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData thermometer = IconData(0xe9ea,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData thumbsDown = IconData(0xe9eb,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData thumbsUp = IconData(0xe9ec,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData toggleLeft = IconData(0xe9ed,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData toggleRight = IconData(0xe9ee,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData trash2 = IconData(0xe9ef,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData trash = IconData(0xe9f0,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData trello = IconData(0xe9f1,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData trendingDown = IconData(0xe9f2,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData trendingUp = IconData(0xe9f3,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData triangle = IconData(0xe9f4,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData truck = IconData(0xe9f5,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData tv = IconData(0xe9f6,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData twitter = IconData(0xe9f7,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData type = IconData(0xe9f8,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData umbrella = IconData(0xe9f9,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData underline = IconData(0xe9fa,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData unlock = IconData(0xe9fb,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData uploadCloud = IconData(0xe9fc,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData upload = IconData(0xe9fd,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData userCheck = IconData(0xe9fe,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData userMinus = IconData(0xe9ff,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData userPlus = IconData(0xea00,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData userX = IconData(0xea01,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData user = IconData(0xea02,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData users = IconData(0xea03,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData videoOff = IconData(0xea04,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData video = IconData(0xea05,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData voicemail = IconData(0xea06,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData volume1 = IconData(0xea07,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData volume2 = IconData(0xea08,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData volumeX = IconData(0xea09,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData volume = IconData(0xea0a,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData watch = IconData(0xea0b,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData wifiOff = IconData(0xea0c,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData wifi = IconData(0xea0d,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData wind = IconData(0xea0e,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData xCircle = IconData(0xea0f,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData xOctagon = IconData(0xea10,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData xSquare = IconData(0xea11,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData x = IconData(0xea12,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData youtube = IconData(0xea13,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData zapOff = IconData(0xea14,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData zap = IconData(0xea15,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData zoomIn = IconData(0xea16,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
  static const IconData zoomOut = IconData(0xea17,
      fontFamily: kFeatherFontFamily, fontPackage: kFeatherFontPackage);
}
